### ISSUE TITLE
hide map if no action has geolocation

### ISSUE THREAD

**Issue by hagoptaminian** [graasp/graasp-analytics#39]
for example, spaceId `5ecd105e33c8a33f3d5cec2e` returns 16 actions, but none of them have geolocation data. this is confusing for users (why is the map empty?) 
![Screen Shot 2020-06-24 at 4 06 56 PM](https://user-images.githubusercontent.com/19311953/85562012-c3ef0e80-b634-11ea-8f58-56852317c4ad.png)

**Comment by pyphilia** [comment]
When the map is displayed, also add a alert banner info to let the user know that some actions might not have geolocation.
